packages:
  - studio
  - functions
  - packages/*
  - apps/*

catalog:
  '@sanity/assist': ^6.0.2
  '@sanity/client': ^7.22.0
  '@sanity/document-internationalization': ^6.0.0
  '@sanity/icons': ^3.7.4
  '@sanity/ui': ^3.1.13
  '@sanity/vision': ^6.1.0
  '@types/react': ^19.2
  '@types/react-dom': ^19.2.3
  groq: ^6.1.0
  lucide-react: ^0.574.0
  react: ^19.2
  react-dom: ^19.2
  sanity: ^6.1.0
  sanity-plugin-internationalized-array: ^5.0.0
  styled-components: ^6.3.11
  typescript: ^5.9
  vitest: ^4.0.18
